RePuerta/current/urls.py
from django.urls import path
from . import views

app_name = 'current'

urlpatterns = [
    path('', views.current, name="current"),
    path('keep_frame/', views.keep_frame, name="keep_frame"),
    path('new_frame/', views.new_frame, name="new_frame"),
    path('search_without_frame/', views.search_view, name="search_view"),
    path('search_with_frame/', views.new_frame_view, name="new_frame_view"),
    path('list/', views.doors_list, name="list"),
    path('new-door/', views.door_new, name="new-door"),
    path('page/<int:pk>/', views.doors_page, name="page"),
    path('edit_door/<int:pk>/', views.edit_door, name="edit_door"),
    path('delete_door/<int:pk>/', views.delete_door, name="delete_door"),
    path('edit_marker/<int:pk>/', views.edit_marker, name="edit_marker"),
    path('delete_marker/<int:pk>/', views.delete_marker, name="delete_marker"),
    path('my-uploads/', views.my_uploads, name="my_uploads"),
]

RePuerta/historic/urls.py
from django.urls import path
from . import views
from .views import MarkerListView

app_name = 'historic'

urlpatterns = [
    path('', views.map_view, name='map_view'),
    path('api/markers/', MarkerListView.as_view(), name='marker-list'),
    path('map/', views.map_view, name='map'),
    path('marker/', views.marker, name='marker'),
    path('map/info/<int:pk>/', views.marker_info, name='marker_info'),
]

RePuerta/myproject/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve
from historic.views import map_view

urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve,
            {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve,
            {'document_root': settings.STATIC_ROOT}),
    path('admin/', admin.site.urls),
    path('', views.homepage, name='home'),
    path('users/', include('users.urls')),
    path('repare/', views.repare),
    path('replace/', views.replace, name='replace'),
    path('replace_current/', include('current.urls')),
    path('replace_historic/', include('historic.urls')),
    path('', map_view, name='map'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

RePuerta/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register_view, name="register"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
]

RePuerta/historic/models.py
from django.db import models
from django.contrib.auth.models import User


class Marker(models.Model):
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to='markers/')
    latitude = models.FloatField()
    longitude = models.FloatField()
    description = models.TextField(blank=True, null=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

RePuerta/historic/forms.py
from django import forms
from . import models


class AddMarker(forms.ModelForm):
    class Meta:
        model = models.Marker
        fields = ['name', 'image', 'latitude', 'longitude', 'description']

RePuerta/RePuerta/historic/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Marker
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse

# Create your views here.

from rest_framework.views import APIView
from rest_framework.response import Response
from .models import Marker
from .serializers import MarkerSerializer
from django.http import JsonResponse
from django.core.serializers import serialize
from .forms import AddMarker
from . import forms


def map_view(request):
    markers = Marker.objects.all()

    # Serialize data for safe usage in JS.
    serialized_markers = serialize('json', markers)

    # Debugging: Print serialized data in the console
    print(serialized_markers)

    return render(request, 'mapapp/map.html', {'markers': serialized_markers})


class MarkerListView(APIView):
    def get(self, request):
        markers = Marker.objects.all()
        serializer = MarkerSerializer(markers, many=True)
        return Response(serializer.data)


# def marker_info(request, pk):
#     marker = get_object_or_404(Marker, pk=pk)

#     return render(request, 'mapapp/info.html', {'marker': marker})

def marker_info(request, pk):
    # Get marker object by primary key
    marker = get_object_or_404(Marker, pk=pk)

    # Render the info page template with marker details
    return render(request, 'mapapp/info.html', {'marker': marker})


def map_view(request):
    # Serialize marker data to JSON
    markers = Marker.objects.all()
    serialized_markers = serialize('json', markers)

    # Pass the serialized data to the template
    return render(request, 'mapapp/map.html', {'markers': serialized_markers})


# @login_required(login_url="/users/login/")
# def marker(request):
#     if request.method == 'POST':
#         form = AddMarker(request.POST, request.FILES)
#         if form.is_valid():
#             newpost = form.save(commit=False)
#             newpost.author = request.user
#             newpost.save()
#             return redirect('historic:map')
#         else:
#             print(form.errors)  # Debugging: Print form validation errors
#     else:
#         form = AddMarker()
#     return render(request, 'mapapp/new-marker.html', {'form': form})


@login_required(login_url="/users/login/")
def marker(request):
    if request.method == 'POST':
        print("POST data:", request.POST)  # Debug form data
        print("FILES data:", request.FILES)  # Debug uploaded files
        form = AddMarker(request.POST, request.FILES)
        if form.is_valid():
            print("Form is valid")  # Debug
            newpost = form.save(commit=False)
            newpost.author = request.user  # Automatically set the author
            newpost.save()
            return redirect('historic:map')
        else:
            print("Form errors:", form.errors)  # Debug
            # Return errors for easier debugging
            return JsonResponse({"errors": form.errors}, status=400)
    else:
        print("GET request received")  # Debug
        form = AddMarker()
    return render(request, 'mapapp/new_marker.html', {'form': form})

RePuerta/historic/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Marker
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from rest_framework.views import APIView
from rest_framework.response import Response
from .serializers import MarkerSerializer
from django.core.serializers import serialize
from .forms import AddMarker

# Create your views here.


def map_view(request):
    markers = Marker.objects.all()

    # Serialize data for safe usage in JS.
    serialized_markers = serialize('json', markers)

    return render(request, 'mapapp/map.html', {'markers': serialized_markers})


class MarkerListView(APIView):
    def get(self, request):
        markers = Marker.objects.all()
        serializer = MarkerSerializer(markers, many=True)
        return Response(serializer.data)


def marker_info(request, pk):
    # Get marker object by primary key
    marker = get_object_or_404(Marker, pk=pk)

    # Render the info page template with marker details
    return render(request, 'mapapp/info.html', {'marker': marker})


def map_view(request):
    # Serialize marker data to JSON
    markers = Marker.objects.all()
    serialized_markers = serialize('json', markers)

    # Pass the serialized data to the template
    return render(request, 'mapapp/map.html', {'markers': serialized_markers})


@login_required(login_url="/users/login/")
def marker(request):
    if request.method == 'POST':
        form = AddMarker(request.POST, request.FILES)
        if form.is_valid():
            newpost = form.save(commit=False)
            newpost.author = request.user  # Automatically set the author
            newpost.save()
            return redirect('historic:map')
    else:
        form = AddMarker()
    return render(request, 'mapapp/new_marker.html', {'form': form})

RePuerta/historic/templates/mapapp/info.html
{% extends 'layout.html' %}


<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>House Information</title>
    {% block title %}
    {{ marker.name }}
    {% endblock %}
</head>
<body>
    {% block content %}
    <div class="studies_section layout_padding">
        <div class="container">
           <div class="row">
              <div class="col-md-6">
                 <div class="about_img"><img src="{{ marker.image.url }}"></div>
              </div>
              <div class="col-md-6">
                 <div class="about_text_main">
                    <h1 class="about_taital">{{ marker.name }}</h1>
                    <div class="about_text">
                        <p><span style="font-weight:bold;">Latitude:</span> {{ marker.latitude }}</p>
                        <p><span style="font-weight:bold;">Longitude:</span> {{ marker.longitude }}</p>
                        <p><span style="font-weight:bold;">Description:</span> </p>
                        <p>{{ marker.description }}</p>
                    </div>
                    <div class="back_btn"><a href="{% url 'historic:map' %}">Back to map</a></div>
                    <div class="find_btn"><a href="{% url 'current:new_frame' %}">Find door</a></div>
                 </div>
              </div>
           </div>
        </div>
     </div>
    {% endblock %}
</body>
</html>

RePuerta/historic/templates/mapapp/map.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
   <!-- head and navbar added separately so they don't mess up the map -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Map with Markers</title>
    <link rel="stylesheet" href="https://unpkg.com/leaflet/dist/leaflet.css"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <!-- bootstrap css -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <!-- Responsive-->
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
    <!-- fevicon -->
    <link rel="icon" href="{% static 'images/fevicon.png' %}" type="image/gif" />
    <!-- font css -->
    <link href="https://fonts.googleapis.com/css2?family=Sen:wght@400;700;800&display=swap" rel="stylesheet">
    <!-- Scrollbar Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/jquery.mCustomScrollbar.min.css' %}">
    <!-- Tweaks for older IEs-->
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
    <style>
        #map { height: 550px; margin: 20px 20px}
        .marker-icon {
            width: 30px;
            height: 30px;
        }
    </style>
</head>
<body>
      <div class="header_section">
               <div class="navbar-fluid">
                  <nav class="navbar navbar-expand-lg navbar-light">
                     <a class="navbar-brand"href="/">
                        <img class= "logo_img" src="{% static 'images/logo-white.png' %}"></a>
                     <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                     <span class="navbar-toggler-icon"></span>
                     </button>
                     <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav mr-auto">
                           <li class="nav-item active">
                              <a class="nav-link" href="/">Home</a>
                           </li>
                           <li class="nav-item">
                              <a class="nav-link" href="{% url 'historic:map' %}">Historic map</a>
                           </li>
                           <li class="nav-item">
                              <a class="nav-link" href="{% url 'replace' %}">Find door</a>
                           </li>
                           <li class="nav-item">
                              <a class="nav-link" href="{% url 'current:list' %}">Doors for sale</a>
                           </li>
                           <li class="nav-item">
                              <a class="nav-link" href="{% url 'current:new-door' %}">Sell door</a>
                           </li>
                           <li class="nav-item">
                              <a class="nav-link" href="{% url 'current:my_uploads' %}">My Uploads</a>
                           </li>
   
                        </ul>
                        {% if user.is_authenticated %}
                        <form class="form-inline my-2 my-lg-0">
                           <div class="login_bt">
                              <ul>
                                 <li><a href="{% url 'users:logout' %}"><span class="user_icon"><i class="fa fa-user" aria-hidden="true"></i></span>Logout</a></li>
                              </ul>
                           </div>
                        {% else %}
                        <form class="form-inline my-2 my-lg-0">
                           <div class="login_bt">
                              <ul>
                                 <li><a href="{% url 'users:login' %}"><span class="user_icon"><i class="fa fa-user" aria-hidden="true"></i></span>Login</a></li>
                                 <li><a href="{% url 'users:register' %}"><span class="user_icon"><i class="fa fa-user" aria-hidden="true"></i></span>Register</a></li>
                              </ul>
                           </div>
                        </form>
                        {% endif %}
                     </div>
                  </nav>
               </div>
            </div>
    <div class="header_section">
        
    
    {% block content %}
    
      
               
                  <div class="row">
                     <div class="col-md-12">
                        <div class="newsletter_section"> 
                           <h1 class="banner_taital">Historic views</h1>
                           <p class="banner_text">Click on a marker to find out, what the house might have looked like originally. If you have historic information and images of other houses, you can also add a new marker. </p>
                        </div>
                     </div>
                  </div>
               
<div id="map"></div>

<script src="https://unpkg.com/leaflet/dist/leaflet.js"></script>
<script>
    // Ensure markers data is available as JSON
    var markers = {{ markers|safe }};
    
    // Initialize the map
    var map = L.map('map').setView([23.129046, -82.365061], 17); // Set initial view coordinates and zoom level
    
    // Add a Mapbox Tile Layer
    L.tileLayer("https://api.mapbox.com/styles/v1/mapbox/light-v11/tiles/{z}/{x}/{y}?access_token={accessToken}", {
        id: "mapbox/streets-v11", // Use the desired Mapbox style (see below for options)
        accessToken: "pk.eyJ1IjoicmViZWtrYWEiLCJhIjoiY202NmN0MHpjMDA2ODJxcXBheXY1ZDlrYSJ9.lRsG2DbtX-FQ4MylMDOjnw",
        tileSize: 512, // Required for Mapbox tiles
        zoomOffset: -1, // Required for Mapbox tiles
        attribution: '© <a href="https://www.mapbox.com/">Mapbox</a> contributors'
    }).addTo(map);

    
    // Loop through each marker and add it to the map
    markers.forEach(function(marker) {
         // Use the default Leaflet marker icon
        var markerInstance = L.marker([marker.fields.latitude, marker.fields.longitude]).addTo(map);
        var icon = L.icon({
            iconUrl: marker.fields.image_url, // Ensure your model has an image field for markers
            iconSize: [30, 30], // Size of the marker image
            className: 'marker-icon'
        });
    
    
        // Bind click event to redirect to house info page
        markerInstance.on('click', function() {
            window.location.href = 'info/' + marker.pk; // Redirect to info page with marker ID
        });
    });
    </script>

    <div class="read_bt"><a href="{% url 'historic:marker' %}">Add new marker</a></div>
    {% endblock %}
</body>
</html>

RePuerta/historic/templates/mapapp/new_marker.html
{% extends 'layout.html' %}
<!DOCTYPE html>

{% block title %}
    Add new marker
{% endblock %}

{% block content %}
    <section>   
        <div class="contact_section layout_padding">
            <div class="container">
               <div class="row">
                  <div class="col-md-12">
                     <h1 class="contact_taital">Add new marker</h1>
                  </div>
               </div>
               <div class="contact_section_2">
                  <div class="row">
                     <div class="col-md-8">
                        <div class=".cta-form"> 
                            </form> {% comment %} without this line, the form doesn't work {% endcomment %}
                            <form class="form" action="{% url 'historic:marker' %}" method="post" enctype="multipart/form-data">
                              {% csrf_token %}
                              {{ form.as_p }}
                              <button class="readmore_btn">Add Post</button>
                            </form>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
    </section>
{% endblock %}