RePuerta/current/urls.py
from django.urls import path
from . import views

app_name = 'current'

urlpatterns = [
    path('', views.current, name="current"),
    path('keep_frame/', views.keep_frame, name="keep_frame"),
    path('new_frame/', views.new_frame, name="new_frame"),
    path('search_without_frame/', views.search_view, name="search_view"),
    path('search_with_frame/', views.new_frame_view, name="new_frame_view"),
    path('list/', views.doors_list, name="list"),
    path('new-door/', views.door_new, name="new-door"),
    path('page/<int:pk>/', views.doors_page, name="page"),
    path('edit_door/<int:pk>/', views.edit_door, name="edit_door"),
    path('delete_door/<int:pk>/', views.delete_door, name="delete_door"),
    path('edit_marker/<int:pk>/', views.edit_marker, name="edit_marker"),
    path('delete_marker/<int:pk>/', views.delete_marker, name="delete_marker"),
    path('my-uploads/', views.my_uploads, name="my_uploads"),
]

RePuerta/historic/urls.py
from django.urls import path
from . import views
from .views import MarkerListView

app_name = 'historic'

urlpatterns = [
    path('', views.map_view, name='map_view'),
    path('api/markers/', MarkerListView.as_view(), name='marker-list'),
    path('map/', views.map_view, name='map'),
    path('marker/', views.marker, name='marker'),
    path('map/info/<int:pk>/', views.marker_info, name='marker_info'),
]

RePuerta/myproject/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve
from historic.views import map_view

urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve,
            {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve,
            {'document_root': settings.STATIC_ROOT}),
    path('admin/', admin.site.urls),
    path('', views.homepage, name='home'),
    path('users/', include('users.urls')),
    path('repare/', views.repare),
    path('replace/', views.replace, name='replace'),
    path('replace_current/', include('current.urls')),
    path('replace_historic/', include('historic.urls')),
    path('', map_view, name='map'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

RePuerta/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register_view, name="register"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
]

RePuerta/templates/about.html
<!DOCTYPE html>
<html>
   <head>
      <!-- basic -->
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <!-- mobile metas -->
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="viewport" content="initial-scale=1, maximum-scale=1">
      <!-- site metas -->
      <title>About</title>
      <meta name="keywords" content="">
      <meta name="description" content="">
      <meta name="author" content="">
      <!-- bootstrap css -->
      <link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
      <!-- style css -->
      <link rel="stylesheet" type="text/css" href="css/style.css">
      <!-- Responsive-->
      <link rel="stylesheet" href="css/responsive.css">
      <!-- fevicon -->
      <link rel="icon" href="images/fevicon.png" type="image/gif" />
      <!-- font css -->
      <link href="https://fonts.googleapis.com/css2?family=Sen:wght@400;700;800&display=swap" rel="stylesheet">
      <!-- Scrollbar Custom CSS -->
      <link rel="stylesheet" href="css/jquery.mCustomScrollbar.min.css">
      <!-- Tweaks for older IEs-->
      <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
   </head>
   <body>
      <div class="header_section">
         <div class="container-fluid">
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
               <a class="navbar-brand"href="index.html"><img src="images/logo.png"></a>
               <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
               <span class="navbar-toggler-icon"></span>
               </button>
               <div class="collapse navbar-collapse" id="navbarSupportedContent">
                  <ul class="navbar-nav mr-auto">
                     <li class="nav-item">
                        <a class="nav-link" href="index.html">Home</a>
                     </li>
                     <li class="nav-item active">
                        <a class="nav-link" href="about.html">About</a>
                     </li>
                     <li class="nav-item">
                        <a class="nav-link" href="what-we.html">What we do</a>
                     </li>
                     <li class="nav-item">
                        <a class="nav-link" href="blog.html">Blog</a>
                     </li>
                     <li class="nav-item">
                        <a class="nav-link" href="contact.html">Contact Us</a>
                     </li>
                  </ul>
                  <form class="form-inline my-2 my-lg-0">
                     <div class="login_bt">
                        <ul>
                           <li><a href="#"><span class="user_icon"><i class="fa fa-user" aria-hidden="true"></i></span>Login</a></li>
                           <li><a href="#"><i class="fa fa-search" aria-hidden="true"></i></a></li>
                        </ul>
                     </div>
                  </form>
               </div>
            </nav>
         </div>
      </div>
      <!-- header section end -->
      <!-- about section start -->
      <div class="about_section layout_padding margin_top90">
         <div class="container">
            <div class="row">
               <div class="col-md-6">
                  <div class="about_img"><img src="images/about-img.png"></div>
               </div>
               <div class="col-md-6">
                  <div class="about_text_main">
                     <h1 class="about_taital">About Us</h1>
                     <p class="about_text">anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet</p>
                     <div class="readmore_bt"><a href="#">Read More</a></div>
                  </div>
               </div>
            </div>
         </div>
      </div>
      <!-- about section end -->
      <!-- footer section start -->
      <div class="footer_section layout_padding">
         <div class="container">
            <div class="row">
               <div class="col-md-12">
                  <div class="location_text">
                     <ul>
                        <li>
                           <a href="#"><i class="fa fa-map-marker" aria-hidden="true"></i></a>
                        </li>
                        <li>
                           <a href="#"><i class="fa fa-phone" aria-hidden="true"></i></a>
                        </li>
                        <li>
                           <a href="#"><i class="fa fa-envelope" aria-hidden="true"></i></a>
                        </li>
                     </ul>
                  </div>
               </div>
               <div class="footer_logo">
                  <a href="indexz.html">
                     <img src="images/logo.png">
               </div>
               <div class="social_icon">
               <ul>
               <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
               <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
               <li><a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
               </ul>
               </div>
            </div>
         </div>
      </div>
      <!-- footer section end -->
      <!-- copyright section start -->
      <div class="copyright_section">
         <div class="container">
            <p class="copyright_text">2020 All Rights Reserved. Design by <a href="https://html.design">Free Html Templates</a></p>
         </div>
      </div>
      <!-- copyright section end -->
      <!-- Javascript files-->
      <script src="js/jquery.min.js"></script>
      <script src="js/popper.min.js"></script>
      <script src="js/bootstrap.bundle.min.js"></script>
      <script src="js/jquery-3.0.0.min.js"></script>
      <script src="js/plugin.js"></script>
      <!-- sidebar -->
      <script src="js/jquery.mCustomScrollbar.concat.min.js"></script>
      <script src="js/custom.js"></script>
      <!-- javascript --> 
   </body>
</html>

RePuerta/templates/home.html
<!DOCTYPE html>
{% load static %}
<html>
   
   <head>
      <!-- basic -->
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <!-- mobile metas -->
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="viewport" content="initial-scale=1, maximum-scale=1">
      <!-- site metas -->
      
      <title>
         {% block title %}
         RePuerta
         {% endblock %}
      </title>
      <meta name="keywords" content="">
      <meta name="description" content="">
      <meta name="author" content="">
      <!-- bootstrap css -->
      <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
      <!-- style css -->
      <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
      <!-- Responsive-->
      <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
      <!-- fevicon -->
      <link rel="icon" href="{% static 'images/fevicon.png' %}" type="image/gif" />
      <!-- font css -->
      <link href="https://fonts.googleapis.com/css2?family=Sen:wght@400;700;800&display=swap" rel="stylesheet">
      <!-- Scrollbar Custom CSS -->
      <link rel="stylesheet" href="{% static 'css/jquery.mCustomScrollbar.min.css' %}">
      <!-- Tweaks for older IEs-->
      <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
   </head>
   
   <body>
      <nav> 
         <div class="header_section">
               <div class="navbar-fluid">
                  <nav class="navbar navbar-expand-lg navbar-light bg-light">
                     <a class="navbar-brand"href="/">
                        <img class= "logo_img" src="{% static 'images/logo-white.png' %}"></a>
                     <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                     <span class="navbar-toggler-icon"></span>
                     </button>
                     <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav mr-auto">
                           <li class="nav-item active">
                              <a class="nav-link" href="/">Home</a>
                           </li>
                           <li class="nav-item">
                              <a class="nav-link" href="{% url 'historic:map' %}">Historic map</a>
                           </li>
                           <li class="nav-item">
                              <a class="nav-link" href="{% url 'replace' %}">Find door</a>
                           </li>
                           <li class="nav-item">
                              <a class="nav-link" href="{% url 'current:list' %}">Doors for sale</a>
                           </li>
                           <li class="nav-item">
                              <a class="nav-link" href="{% url 'current:new-door' %}">Sell door</a>
                           </li>
                           <li class="nav-item">
                              <a class="nav-link" href="{% url 'current:my_uploads' %}">My Uploads</a>
                           </li>
   
                        </ul>
                        {% if user.is_authenticated %}
                        <form class="form-inline my-2 my-lg-0">
                           <div class="login_bt">
                              <ul>
                                 <li><a href="{% url 'users:logout' %}"><span class="user_icon"><i class="fa fa-user" aria-hidden="true"></i></span>Logout</a></li>
                              </ul>
                           </div>
                        {% else %}
                        <form class="form-inline my-2 my-lg-0">
                           <div class="login_bt">
                              <ul>
                                 <li><a href="{% url 'users:login' %}"><span class="user_icon"><i class="fa fa-user" aria-hidden="true"></i></span>Login</a></li>
                                 <li><a href="{% url 'users:register' %}"><span class="user_icon"><i class="fa fa-user" aria-hidden="true"></i></span>Register</a></li>
                              </ul>
                           </div>
                        </form>
                        {% endif %}
                     </div>
                  </nav>
               </div>
            </div>
      </nav>
         <!-- banner section start --> 

         {% block carouselbanner %}
         <div class="banner_section layout_padding">
            <div class=".container-fluid">
               <div id="banner_slider" class="carousel slide" data-ride="carousel">
                  <div class="carousel-inner">
                     <div class="carousel-item active">
                        <div class="row">
                           <div class="col-md-6">
                              <div class="banner_taital_main">
                                 <h1 class="banner_taital">Find a replacement for your broken door</h1>
                                 <p class="banner_text">Your doors is broken and you want to find a new one? Click here to start the process of finding a match from your community.</p>
                                 <div class="readmore_btn active"><a href="/replace">Start now</a></div>
                              </div>
                           </div>
                           <div class="col-md-6">
                              <div class="banner_img"><img src="{% static 'images/pikto-current.png' %}"></div>
                           </div>
                        </div>
                     </div>
                     <div class="carousel-item">
                        <div class="row">
                           <div class="col-md-6">
                              <div class="banner_taital_main">
                                 <h1 class="banner_taital">Find historic inspiration</h1>
                                 <p class="banner_text">You want to learn more about what your neighborhood might have looked like originally? Click here to find sketches and images of original facades around your neighborhood</p>
                                 <div class="readmore_btn active"><a href="/replace_historic">Find out more</a></div>
                              </div>
                           </div>
                           <div class="col-md-6">
                              <div class="banner_img"><img src="{% static 'images/pikto-historic.png' %}"></div>
                           </div>
                        </div>
                     </div>
                  </div>
                  <a class="carousel-control-prev" href="#banner_slider" role="button" data-slide="prev">
                  <i class="fa fa-arrow-left"></i>
                  </a>
                  <a class="carousel-control-next" href="#banner_slider" role="button" data-slide="next">
                  <i class="fa fa-arrow-right"></i>
                  </a>
               </div>
            </div>
         </div>
         {% endblock %}
         <!-- banner section end -->
      </div>

      <!-- Javascript files-->
      <script src="{% static 'js/jquery.min.js' %}"></script>
      <script src="{% static 'js/popper.min.js' %}"></script>
      <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
      <script src="{% static 'js/jquery-3.0.0.min.js' %}"></script>
      <script src="{% static 'js/plugin.js' %}"></script>
      <!-- sidebar -->
      <script src="{% static 'js/jquery.mCustomScrollbar.concat.min.js' %}"></script>
      <script src="{% static 'js/custom.js' %}"></script>
      <!-- javascript -->
   </body>
</html>

RePuerta/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    </title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- basic -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- mobile metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">
    <!-- site metas -->
    
    <title>
       {% block title %}
       RePuerta
       {% endblock %}
    </title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- bootstrap css -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <!-- style css -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <!-- Responsive-->
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
    <!-- fevicon -->
    <link rel="icon" href="{% static 'images/fevicon.png' %}" type="image/gif" />
    <!-- font css -->
    <link href="https://fonts.googleapis.com/css2?family=Sen:wght@400;700;800&display=swap" rel="stylesheet">
    <!-- Scrollbar Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/jquery.mCustomScrollbar.min.css' %}">
    <!-- Tweaks for older IEs-->
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
</head>
<body>
   <nav> 
      <div class="header_section">
            <div class="navbar-fluid">
               <nav class="navbar navbar-expand-lg navbar-light bg-light">
                  <a class="navbar-brand"href="/">
                     <img class= "logo_img" src="{% static 'images/logo-white.png' %}"></a>
                  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                  </button>
                  <div class="collapse navbar-collapse" id="navbarSupportedContent">
                     <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                           <a class="nav-link" href="/">Home</a>
                        </li>
                        <li class="nav-item">
                           <a class="nav-link" href="{% url 'historic:map' %}">Historic map</a>
                        </li>
                        <li class="nav-item">
                           <a class="nav-link" href="{% url 'replace' %}">Find door</a>
                        </li>
                        <li class="nav-item">
                           <a class="nav-link" href="{% url 'current:list' %}">Doors for sale</a>
                        </li>
                        <li class="nav-item">
                           <a class="nav-link" href="{% url 'current:new-door' %}">Sell door</a>
                        </li>
                        <li class="nav-item">
                           <a class="nav-link" href="{% url 'current:my_uploads' %}">My Uploads</a>
                        </li>

                     </ul>
                     {% if user.is_authenticated %}
                     <form class="form-inline my-2 my-lg-0">
                        <div class="login_bt">
                           <ul>
                              <li><a href="{% url 'users:logout' %}"><span class="user_icon"><i class="fa fa-user" aria-hidden="true"></i></span>Logout</a></li>
                           </ul>
                        </div>
                     {% else %}
                     <form class="form-inline my-2 my-lg-0">
                        <div class="login_bt">
                           <ul>
                              <li><a href="{% url 'users:login' %}"><span class="user_icon"><i class="fa fa-user" aria-hidden="true"></i></span>Login</a></li>
                              <li><a href="{% url 'users:register' %}"><span class="user_icon"><i class="fa fa-user" aria-hidden="true"></i></span>Register</a></li>
                           </ul>
                        </div>
                     </form>
                     {% endif %}
                  </div>
               </nav>
            </div>
         </div>
   </nav>
   <main>
      {% block content %}
      {% endblock %}
      {% block more %}
      {% endblock %}
   </main>
   <!-- Javascript files-->
   <script src="{% static 'js/jquery.min.js' %}"></script>
   <script src="{% static 'js/popper.min.js' %}"></script>
   <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
   <script src="{% static 'js/jquery-3.0.0.min.js' %}"></script>
   <script src="{% static 'js/plugin.js' %}"></script>
   <!-- sidebar -->
   <script src="{% static 'js/jquery.mCustomScrollbar.concat.min.js' %}"></script>
   <script src="{% static 'js/custom.js' %}"></script>
   <!-- javascript -->
</body>

</html>

RePuerta/templates/repare.html
{% extends 'layout.html' %}

{% block title %}
    Repare
{% endblock %}


{% block content %}
    <h1>You want to repare your door</h1>
    <p>Follow this link to find helpful ressources.</p> {% comment %} # Link zu repare Modul einfügen. {% endcomment %}
{% endblock %}

RePuerta/templates/replace.html
{% extends 'layout.html' %}

{% block title %}
    Replace your door
{% endblock %}

{% block content %}
<div class="studies_section layout_padding">
    <div class="container">
       <div class="row">
          <div class="col-md-4">
            <h1 class="about_taital">Replace your door</h1>
            <div class="about_text">
                 <p>Do you want to replace it in its current size and position or do you want to have a look how it might have looked historically?</p>
            </div>
          </div>
          <div class="col-md-4">
             <div class="about_text_main">
                <div class="tomap_bt active"><a href="/replace_current">Keep the current size</a></div>
             </div>
         </div>
          <div class="col-md-4">
             <div class="about_text_main">
                <div class="started_bt"><a href="/replace_historic">Find historic views</a></div>
             </div>
          </div>
       </div>
    </div>
 </div>
{% endblock %}